name: 04 - Using Action

<<<<<<< HEAD
on: push
=======
on: workflow_dispatch
>>>>>>> refs/remotes/origin/main

jobs:
  build:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Printing folders
          run: ls

    # 0. checkout the code from the repository
=======
    defaults:
        run:
          working-directory: 04-using-actions/react-app
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        - name: Install Dependencies
          run: npm ci
        - name: Run Unit Tests
          run: npm run test

>>>>>>> refs/remotes/origin/main
    # 1. Install deps of our react application
    # 2. Execute automated tests